### ISSUE TITLE
problems with installation

### ISSUE THREAD

**Issue by bsnyh** [transitland/transitland-processing-animation#12]
Hi, Thank you so much for this repository. It's really useful. 
I was trying to install it earlier and was not sure about certain steps following your instructions. 
I'm using Linux Ubuntu. The following is the steps to install Processing based on your read me file. 
```
    1: Download Processing 3.
    2: Download Unfolding Maps version 0.9.9 for Processing 3.
    3: Navigate to ~/Documents/Processing/libraries on your machine.
    4: Drag and drop the unzipped Unfolding Maps folder into ~/Documents/Processing/libraries.
    5: Open Processing, navigate to Sketch > Import Library > Add Libary. Search for "Video Export" and click Install.
    6: Quit and re-open Processing.
```
I'm not exactly sure about the step 3 and step 4. More explicitly, how to find the ~/Documents/Processing/libraries folder? I have Processing 3 installed in my home folder. So, I can find ~/Processing folder, and inside of this folder, I have 
```
devel@hpz4:~/processing$ ls
core  install.sh  java  lib  modes  processing  processing-java  revisions.txt  tools  uninstall.sh
devel@hpz4:~/processing$ 
```
So, what shall I do then? 

I finally choose to use the lib folder. I mean, I drag and drop the unzipped Unfolding Maps into 
~/Processing/lib. 

Eventually, when I tried the first example following the read me file,  the output is as the following. 
```
devel@hpz4:~/Desktop/python_begin_again/transitland/transitflow$ python2 transitflow.py --name=bart --operator=o-9q9-bart

INPUTS:
date:  2019-03-02
name:  bart
API key:  None
1 operators to be downloaded.

o-9q9-bart 1 / 1
http://transit.land/api/v1/routes?per_page=10000&operated_by=o-9q9-bart
12 routes found.

http://transit.land/api/v1/stops?per_page=10000&served_by=o-9q9-bart
50 stops found.

http://transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&per_page=10000&sort_min_id=0&operator_onestop_id=o-9q9-bart
9301 schedule stop pairs found.

success!

1 operators successfully downloaded.
0 operators failed.
Concatenating individual operator outputs.
Calculating trip segment bearings.
Total rows:  9301
Counting number of vehicles in transit.
Time elapsed:  0:00:24.503688
```
and 

```
devel@hpz4:~/Desktop/python_begin_again/transitland/transitflow$ python2 transitflow.py --name=chicago --bbox=-87.992249,41.605175,-87.302856,42.126747 --clip_to_bbox --exclude=o-9-amtrak,o-9-amtrakcharteredvehicle

INPUTS:
date:  2019-03-02
name:  chicago
API key:  None
exclude:  ['o-9-amtrakcharteredvehicle', 'o-9-amtrak']
bbox:  -87.992249 41.605175 -87.302856 42.126747

http://transit.land/api/v1/operators?per_page=10000&bbox=-87.992249%2C41.605175%2C-87.302856%2C42.126747
5 operators in bounding box.
3 operators to be downloaded.

o-dp3-pace 1 / 3
http://transit.land/api/v1/routes?per_page=10000&operated_by=o-dp3-pace
228 routes found.

http://transit.land/api/v1/stops?per_page=10000&served_by=o-dp3-pace
https://api.transit.land/api/v1/stops?offset=10000&per_page=10000&served_by=o-dp3-pace&sort_key=id&sort_order=asc
https://api.transit.land/api/v1/stops?offset=20000&per_page=10000&served_by=o-dp3-pace&sort_key=id&sort_order=asc
25556 stops found.

http://transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&per_page=10000&sort_min_id=0&operator_onestop_id=o-dp3-pace
10000
https://api.transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&operator_onestop_id=o-dp3-pace&per_page=10000&sort_key=id&sort_min_id=4707804518&sort_order=asc
20000
https://api.transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&operator_onestop_id=o-dp3-pace&per_page=10000&sort_key=id&sort_min_id=4707819294&sort_order=asc
30000
https://api.transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&operator_onestop_id=o-dp3-pace&per_page=10000&sort_key=id&sort_min_id=4707864774&sort_order=asc
40000
https://api.transit.land/api/v1/schedule_stop_pairs?date=2019-03-02&operator_onestop_id=o-dp3-pace&per_page=10000&sort_key=id&sort_min_id=4707904035&sort_order=asc
retry 1 / 5: HTTP Error 502: Bad Gateway
retry 2 / 5: HTTP Error 502: Bad Gateway
retry 3 / 5: HTTP Error 502: Bad Gateway
retry 4 / 5: HTTP Error 502: Bad Gateway
retry 5 / 5: HTTP Error 502: Bad Gateway
failed:
HTTP Error 502: Bad Gateway
o-dp3-chicagotransitauthority 2 / 3
http://transit.land/api/v1/routes?per_page=10000&operated_by=o-dp3-chicagotransitauthority
retry 1 / 5: HTTP Error 502: Bad Gateway
retry 2 / 5: HTTP Error 502: Bad Gateway
retry 3 / 5: HTTP Error 502: Bad Gateway
137 routes found.

http://transit.land/api/v1/stops?per_page=10000&served_by=o-dp3-chicagotransitauthority
https://api.transit.land/api/v1/stops?offset=10000&per_page=10000&served_by=o-dp3-chicagotransitauthority&sort_key=id&sort_order=asc
retry 1 / 5: HTTP Error 502: Bad Gateway
retry 2 / 5: HTTP Error 502: Bad Gateway
retry 3 / 5: HTTP Error 502: Bad Gateway
retry 4 / 5: HTTP Error 502: Bad Gateway
retry 5 / 5: HTTP Error 502: Bad Gateway
failed:
HTTP Error 502: Bad Gateway
o-dp3-metra 3 / 3
http://transit.land/api/v1/routes?per_page=10000&operated_by=o-dp3-metra
retry 1 / 5: HTTP Error 502: Bad Gateway
retry 2 / 5: HTTP Error 502: Bad Gateway
retry 3 / 5: HTTP Error 502: Bad Gateway
retry 4 / 5: HTTP Error 502: Bad Gateway
retry 5 / 5: HTTP Error 502: Bad Gateway
failed:
HTTP Error 502: Bad Gateway
0 operators successfully downloaded.
3 operators failed.
failed operators: ['o-dp3-pace', 'o-dp3-chicagotransitauthority', 'o-dp3-metra']
Concatenating individual operator outputs.
Traceback (most recent call last):
  File "transitflow.py", line 404, in <module>
    df = concatenate_csvs("sketches/{}/{}/data/indiv_operators".format(OUTPUT_NAME, DATE))
  File "transitflow.py", line 184, in concatenate_csvs
    concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)
  File "/usr/lib/python2.7/dist-packages/pandas/core/reshape/concat.py", line 212, in concat
    copy=copy)
  File "/usr/lib/python2.7/dist-packages/pandas/core/reshape/concat.py", line 245, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

Any comments are greatly appreciated.

**Comment by afunTW** [comment]
I installed processing v3.5.3 on Ubuntu 18.04.3 LTS which will create the folder `~/sketchbook/libraries`.

So I copy the unzip Unfolding Map package to `~/sketchbook/libraries` and run the demo command `python transitflow.py --name=san_francisco --bbox=-122.515411,37.710714,-122.349243,37.853983 --clip_to_bbox` and it finally works
